"""empty message

Revision ID: 45917e595576
Revises: 6051f932d06f
Create Date: 2023-06-16 15:50:19.978574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45917e595576'
down_revision = '6051f932d06f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salt', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('hashed_password', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('role', sa.String(length=80), nullable=False))
        batch_op.create_unique_constraint(None, ['salt'])
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('role')
        batch_op.drop_column('hashed_password')
        batch_op.drop_column('salt')

    # ### end Alembic commands ###
