"""empty message

Revision ID: 85532f7627ff
Revises: 3e62fa0d5e1a
Create Date: 2023-06-15 14:18:22.903356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85532f7627ff'
down_revision = '3e62fa0d5e1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student__data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cedula', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('apellido', sa.String(length=80), nullable=False),
    sa.Column('carrera', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cedula')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student__data')
    # ### end Alembic commands ###
