"""empty message

Revision ID: cf8612ed0723
Revises: e8d37eaec93c
Create Date: 2023-06-19 20:10:00.823407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf8612ed0723'
down_revision = 'e8d37eaec93c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('studen_grade', schema=None) as batch_op:
        batch_op.drop_constraint('studen_grade_codigo_key', type_='unique')
        batch_op.drop_constraint('studen_grade_notas_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('studen_grade', schema=None) as batch_op:
        batch_op.create_unique_constraint('studen_grade_notas_key', ['notas'])
        batch_op.create_unique_constraint('studen_grade_codigo_key', ['codigo'])

    # ### end Alembic commands ###
