"""empty message

Revision ID: e8d37eaec93c
Revises: e1ce6427bf39
Create Date: 2023-06-19 17:28:20.278808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8d37eaec93c'
down_revision = 'e1ce6427bf39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studen_grade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notas', sa.Integer(), nullable=False),
    sa.Column('materias', sa.String(length=80), nullable=False),
    sa.Column('codigo', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    sa.UniqueConstraint('notas')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('studen_grade')
    # ### end Alembic commands ###
